
import { ServiceProvider } from './types';

const MOCK_REVIEWS = [
  { id: 'r1', user: 'Aditi V.', rating: 5, comment: 'Excellent service! Very polite and professional.', date: 'Today' },
  { id: 'r2', user: 'Rahul K.', rating: 4, comment: 'Highly skilled. Fixed the issue which 3 others couldn\'t.', date: '3 days ago' },
  { id: 'r3', user: 'Sanjana M.', rating: 5, comment: 'Punctual and uses quality genuine spare parts.', date: '2 weeks ago' }
];

export const SERVICE_PROVIDERS: ServiceProvider[] = [
  {
    id: '1',
    name: 'Arjun Mehta',
    category: 'Plumbing',
    location: 'Koramangala, Bangalore',
    availability: 'Available',
    rating: 4.9,
    reviewsCount: 342,
    reviews: MOCK_REVIEWS,
    price: '₹499',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=200',
    lat: 12.9352,
    lng: 77.6245,
    description: 'Specialist in high-pressure bathroom fittings and leakage solutions.',
    longBio: 'With 12 years of experience working with top real estate firms in Bangalore, I provide premium plumbing solutions ranging from Jaquar fittings to complex drainage mapping.',
    skills: ['Hydro-jetting', 'Bathroom Fittings', 'Solar Water Heaters'],
    yearsExperience: 12,
    responseTime: '15 mins',
    verified: true,
    repeatCustomers: 124,
    certifications: ['Master Plumber Assoc.', 'Water Safety Cert'],
    equipment: ['High-Pressure Jetter', 'Thermal Leak Detector', 'Electric Pipe Threader'],
    completedJobs: 1450
  },
  {
    id: '2',
    name: 'Priya Sharma',
    category: 'Beauty',
    location: 'Indiranagar, Bangalore',
    availability: 'Busy',
    rating: 5.0,
    reviewsCount: 189,
    reviews: MOCK_REVIEWS,
    price: '₹1200',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200',
    lat: 12.9784,
    lng: 77.6408,
    description: 'Certified bridal makeup artist and premium skin therapist.',
    longBio: 'Trained at top academies in Mumbai, I bring salon-grade luxury to your home. Expert in HD makeup and organic facials.',
    skills: ['Bridal Makeup', 'O3+ Facials', 'Aromatherapy'],
    yearsExperience: 8,
    responseTime: '30 mins',
    verified: true,
    repeatCustomers: 95,
    certifications: ['MAC Pro Artist', 'Skin Esthetician Diploma'],
    equipment: ['Professional LED Kit', 'Hypoallergenic Makeup', 'Steamers'],
    completedJobs: 820
  },
  {
    id: '3',
    name: 'Rajesh Iyer',
    category: 'Electrical',
    location: 'HSR Layout, Bangalore',
    availability: 'Available',
    rating: 4.8,
    reviewsCount: 256,
    reviews: MOCK_REVIEWS,
    price: '₹350',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    lat: 12.9141,
    lng: 77.6411,
    description: 'Master electrician specializing in UPS/Inverter setups and LED lighting.',
    longBio: 'I specialize in home automation and power backup solutions. I ensure your home is safe from voltage fluctuations with certified earthing solutions.',
    skills: ['Inverter Setup', 'Home Automation', 'Main Line Repair'],
    yearsExperience: 15,
    responseTime: '20 mins',
    verified: true,
    repeatCustomers: 210,
    certifications: ['Grade A Wireman', 'Solar Grid Specialist'],
    equipment: ['Digital Multimeter', 'Insulated Tool Kit', 'Thermal Camera'],
    completedJobs: 2100
  },
  {
    id: '4',
    name: 'Vikram Singh',
    category: 'Mechanic',
    location: 'Whitefield, Bangalore',
    availability: 'Available',
    rating: 4.7,
    reviewsCount: 512,
    reviews: MOCK_REVIEWS,
    price: '₹800',
    avatar: 'https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&q=80&w=200',
    lat: 12.9698,
    lng: 77.7500,
    description: 'On-site car service expert for luxury and German vehicles.',
    longBio: 'Don\'t wait at service centers. I provide full-synthetic oil changes and computer diagnostics at your doorstep.',
    skills: ['Diagnostics', 'Engine Tuning', 'Brake Pad Replacement'],
    yearsExperience: 10,
    responseTime: '45 mins',
    verified: true,
    repeatCustomers: 180,
    certifications: ['Automotive Excellence', 'EV Hybrid Specialist'],
    equipment: ['OBD2 Scanner', 'Hydraulic Jack System', 'Impact Wrenches'],
    completedJobs: 1320
  },
  {
    id: '5',
    name: 'Ananya Rao',
    category: 'Wellness',
    location: 'Bandra West, Mumbai',
    availability: 'Offline',
    rating: 4.9,
    reviewsCount: 88,
    reviews: MOCK_REVIEWS,
    price: '₹1500',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200',
    lat: 19.0596,
    lng: 72.8295,
    description: 'Holistic Yoga instructor and mindfulness coach.',
    longBio: 'Personalized Hatha and Ashtanga yoga sessions designed for the busy professional. Certified from Rishikesh.',
    skills: ['Pranayama', 'Weight Management', 'Stress Relief'],
    yearsExperience: 6,
    responseTime: '1 hour',
    verified: false,
    repeatCustomers: 42,
    certifications: ['Yoga Alliance RYT-500', 'Sound Healing Cert'],
    equipment: ['Natural Cork Mats', 'Aromatherapy Diffusers', 'Singing Bowls'],
    completedJobs: 450
  },
  {
    id: '6',
    name: 'Suresh Kumar',
    category: 'Cleaning',
    location: 'Juhu, Mumbai',
    availability: 'Available',
    rating: 4.6,
    reviewsCount: 742,
    reviews: MOCK_REVIEWS,
    price: '₹299',
    avatar: 'https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?auto=format&fit=crop&q=80&w=200',
    lat: 19.1075,
    lng: 72.8263,
    description: 'Deep cleaning expert for homes, sofas, and mattresses.',
    longBio: 'Using industrial-grade vacuum cleaners and eco-friendly chemicals to ensure your home is 99% germ-free.',
    skills: ['Sofa Shampooing', 'Kitchen Deep Clean', 'Pest Control'],
    yearsExperience: 5,
    responseTime: '25 mins',
    verified: true,
    repeatCustomers: 310,
    certifications: ['Eco-Clean Certified', 'BICS Standard'],
    equipment: ['Steam Cleaner', 'HEPA Vacuum', 'Ozone Generator'],
    completedJobs: 2400
  },
  {
    id: '7',
    name: 'Karan Mehra',
    category: 'Home Maintenance',
    location: 'Powai, Mumbai',
    availability: 'Available',
    rating: 4.8,
    reviewsCount: 120,
    reviews: MOCK_REVIEWS,
    price: '₹400',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    lat: 19.1176,
    lng: 72.9060,
    description: 'Professional painter and wood polisher.',
    longBio: 'I offer Asian Paints certified textures and waterproofing solutions for walls that last for years.',
    skills: ['Waterproofing', 'Wall Textures', 'Wood Polishing'],
    yearsExperience: 11,
    responseTime: '40 mins',
    verified: true,
    repeatCustomers: 64,
    certifications: ['Asian Paints Certified', 'Furniture Finishing Pro'],
    equipment: ['Airless Sprayer', 'Dustless Sander', 'Moisture Meter'],
    completedJobs: 680
  }
];

export const CATEGORIES: string[] = [
  'Plumbing', 'Electrical', 'Tutoring', 'Mechanic', 'Home Maintenance', 'Gardening', 'Cleaning', 'Moving', 'Pet Care', 'Beauty', 'Wellness', 'Appliance Repair', 'AC Repair'
];

export const LOCATIONS: string[] = [
  'Koramangala', 'Indiranagar', 'HSR Layout', 'Whitefield', 'Bandra West', 'Juhu', 'Powai', 'Hauz Khas', 'Gurgaon'
];
